### ISSUE TITLE
Feature: "piston export"

### ISSUE THREAD

**Issue by sminnee** [francois/piston#6]
I've put together a script for extracting changes that you make on a piston imported module, should you wish to contribute them back to the main project.

http://github.com/sminnee/piston-export

Should I look at adding this functionality to piston itself?
Before I do that, do you have any feedback on how to make the script work better?

**Comment by francois** [comment]
Thanks for the tip. If you want to make this a command, go ahead. I think it should be named "piston prepare-patch" or something similar. Look into how git names an equivalent command. Fork and submit!

**Comment by sminnee** [comment]
I think I'll add these commands:

piston format-patch (external dir): Exports changes as a patch file.

piston apply-patch (external dir) (dest repos) (dest branch): Calls format-patch and then applies it to a repository using "git am" (the current behaviour)

**Comment by francois** [comment]
That looks great. Thanks for offering to help!
