### ISSUE TITLE
Doesn't support git tags

### ISSUE THREAD

**Issue by chillu** [francois/piston#9]
The `--commit` argument seems to assume a branch name for git, and `--revision` fails completely.
Example with failing tags:
`piston import --commit 1.1.0 git://github.com/silverstripe-labs/silverstripe-sqlite3.git`

If you look at the `git checkout` command piston performs, its doing `git checkout -b my-1.1.0 origin/1.1.0`.
It should rather be `git checkout -b my-1.1.0 1.1.0`

Example with suggested --tag argument: 
`piston import --tag 1.1.0 git://github.com/silverstripe-labs/silverstripe-sqlite3.git`

The --tag argument would need to be limited to the "git" repo type, as tags don't exist as reliably identifyable structures in svn.

**Comment by francois** [comment]
Hi, thanks for reporting, except I'm not maintaining Piston anymore.

Fork and fix as you wish.

Thanks,
François
